[tool.poetry]
name = "mdi"
version = "0.1.0"
description = "A CLI tool to download and load datasets from S3."
authors = ["Rasmus Jones <rasmus.jones@milestone.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
click = "~8.1.7"
requests = "~2.31.0"
boto3 = "~1.26.161"
pytest = "~7.3.2"
tqdm = "~4.65.2"
datasets = "~2.14.7"
xdg-base-dirs = "~6.0.1"
s3fs = "~2023.6.0"
Pillow = "~10.0.1"

[tool.poetry.group.dev.dependencies]
black = "~23.3.0"
isort = "~5.12.0"
flake8 = "~6.0.0"
flake8-annotations = "~3.0.1"
flake8-black = "~0.3.6"
ipykernel = "~6.25.1"

[tool.poetry.scripts]
mdi = 'mdi.__main__:cli'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
