name: CI/CD Workflow
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["src/**", "tests/**", "pyproject.toml"]
  pull_request:
    branches: [main]
    paths: ["src/**", "tests/**", "pyproject.toml"]

jobs:
  lint:
    name: Lint Code
    uses: ./.github/workflows/lint.yaml
    with:
        python-version-file: "pyproject.toml"

  test:
    name: Run Tests
    needs: lint
    uses: ./.github/workflows/tests.yaml
    with:
        python-version-file: "pyproject.toml"

    