name: 'lint-python'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # oldest supported from https://devguide.python.org/versions/
          cache: poetry
      - run: poetry install
      - run: poetry run black --check .
