name: Build and Push Docker Image
on:
  workflow_call:
    inputs:
      python-version-file::
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs:
  docker_runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ inputs.python-version-file  }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.8
      - name: Build the project
        run: uv build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mdi-runtime
        with:
          context: .
          file: .github/workflows/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
          platforms: linux/amd64
          provenance: false
          sbom: false
          build-args: |
            PYTHON_VERSION=${{ inputs.python-version }}