name: Build and Publish Package

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment prefix (e.g. "testpypi" or "pypi")'
        required: true
        type: string

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: python-package
          path: dist/

      - name: Verify package files
        run: |
          if [ -z "$(ls -A dist/)" ]; then
            echo "❌ No package files found in the artifact"
            exit 1
          fi
          echo "✅ Found the following package files:"
          ls -la dist/

      - name: Publish 📦 to ${{ inputs.environment }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ inputs.environment == 'testpypi' && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
          print-hash: true
          verbose: true