name: Build and Publish Package
on:
  workflow_call:
    inputs:
      should_publish:
        required: true
        type: boolean
        description: "Whether to publish the package or just build it"
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build package
        run: |
          pip install uv
          uv build
      - name: Publish package
        if: inputs.should_publish
        run: |-
          export UV_PUBLISH_TOKEN="__token__"
          uv publish --publish-url ${{ secrets.PYPI_SERVER_URL }}
