name: CI/CD Workflow
on:
  workflow_dispatch:
  push:
    branches: [dip-client]
  pull_request:
jobs:
  ci:
    name: Lint Code
    uses: ./.github/workflows/lint.yml
  cd:
    name: Build and Push Docker Image
    needs: ci
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/docker-push.yml
    secrets: inherit
